import { Title } from "@solidjs/meta";
import { A } from "@solidjs/router";
import BigCard from "~/components/BigCard/BigCard";
import { getDefaultList } from "./api";
import { onMount, createSignal } from "solid-js";
import './main.css'

export default function Home() {
  const [auto_generated_list, setAutoGeneratedList] = createSignal([])
  const [selectedFilter, setSelectedFilter] = createSignal("All")

  /*
  const auto_generated_list = [
    {title: "Lista 1", subtitle: "Lista già pronta", name: "Spesa BBQ", description: "Spesa per la tua grigliata con gli amici", tags: "carne,verdure,salse", color: "red"},
    {title: "Lista 2", subtitle: "Lista già pronta", name: "Spesa Vegana", description: "Spesa economica e super iper vegana!!! ", tags: "verdura,vegana,salutare", color: "green"},
  ]
    */

  onMount(async () => {
    const default_list = await getDefaultList()
    setAutoGeneratedList(default_list)
    console.log(default_list)
  })

  const handleFilterClick = (filter) => {
    setSelectedFilter(filter)
  }

  const filteredList = () => {
    if (selectedFilter() === "All") {
      return auto_generated_list()
    }
    return auto_generated_list().filter(card => 
      card.tags.some(tag => tag.toLowerCase() === selectedFilter().toLowerCase())
    )
  }

  return (
    <main>
      <header>
        <span className="title">Mangia meglio, spreca meno</span>
        <div className="icon">
          <img src="../assets/icons/carrot.svg" alt="" />
        </div>
      </header>

      <div className="list">
        <div className="list-filters">
          <span className="title">Liste già pronte</span>
          <div className="cards-container">
            <div className="cards-slider">
              <button 
                className={`card ${selectedFilter() === "All" ? "sel" : ""}`}
                onClick={() => handleFilterClick("All")}
              >
                All
              </button>
              <button 
                className={`card ${selectedFilter() === "Carne" ? "sel" : ""}`}
                onClick={() => handleFilterClick("Carne")}
              >
                Carne
              </button>
              <button 
                className={`card ${selectedFilter() === "Verdura" ? "sel" : ""}`}
                onClick={() => handleFilterClick("Verdura")}
              >
                Verdura
              </button>
              <button 
                className={`card ${selectedFilter() === "Pasta" ? "sel" : ""}`}
                onClick={() => handleFilterClick("Pasta")}
              >
                Pasta
              </button>
              <button 
                className={`card ${selectedFilter() === "Riso" ? "sel" : ""}`}
                onClick={() => handleFilterClick("Riso")}
              >
                Riso
              </button>
              <button 
                className={`card ${selectedFilter() === "Frutta" ? "sel" : ""}`}
                onClick={() => handleFilterClick("Frutta")}
              >
                Frutta
              </button>
              <button 
                className={`card ${selectedFilter() === "Snack" ? "sel" : ""}`}
                onClick={() => handleFilterClick("Snack")}
              >
                Snack
              </button>
              <button 
                className={`card ${selectedFilter() === "Latticini" ? "sel" : ""}`}
                onClick={() => handleFilterClick("Latticini")}
              >
                Latticini
              </button>
            </div>
          </div>
        </div>

        <div className="big-cards-container">
          <div className="big-cards-slider">
            {filteredList().map((big_card, index) => (
              <BigCard
                title="Liste già pronte"
                subtitle="4 persone"
                name={big_card.nome}
                description={"Durata: " + big_card.durata + " giorni"}
                tags={big_card.tags}
                color={['#56BF6E', '#FF7126', '#8B4513', '#CD853F', '#DEB887'][index % 5]}
              />
            ))}
          </div>
        </div>

        <div className="supermarket-container">
          <div className="title">Supermercati piu vicini</div>
          <div className="cards">
            <div className="card">
              <div className="icon">
                <img
                  src="https://play-lh.googleusercontent.com/qhCk-KOnqgRbly6nRGwlRC9NP1g83zPKR2s5rX_jtRIjfMHh-0AkQoAMmb26hhAavA"
                  alt=""
                />
              </div>
              <div className="text">
                <div className="name">Esselunga</div>
                <span className="distance">500m</span>
              </div>
              <div className="buttons">
                <A href="../"><i className="fa-solid fa-link"></i></A>
              </div>
            </div>

            <div className="card">
              <div className="icon">
                <img
                  src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Lidl_logo.png/960px-Lidl_logo.png"
                  alt=""
                />
              </div>
              <div className="text">
                <div className="name">LIDL</div>
                <span className="distance">2km</span>
              </div>
              <div className="buttons">
                <A href="../"><i className="fa-solid fa-link"></i></A>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
