const nazioniConBandiere = [
    "Italia",
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua e Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaigian",
    "Bahamas",
    "Bahrein",
    "Bangladesh",
    "Barbados",
    "Bielorussia",
    "Belgio",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia ed Erzegovina",
    "Botswana",
    "Brasile",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cambogia",
    "Camerun",
    "Canada",
    "Capo Verde",
    "Repubblica Centrafricana",
    "Ciad",
    "Cile",
    "Cina",
    "Colombia",
    "Comore",
    "Repubblica del Congo",
    "Repubblica Democratica del Congo",
    "Costa Rica",
    "Croazia",
    "Cuba",
    "Cipro",
    "Repubblica Ceca",
    "Danimarca",
    "Gibuti",
    "Dominica",
    "Repubblica Dominicana",
    "Ecuador",
    "Egitto",
    "El Salvador",
    "Guinea Equatoriale",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Etiopia",
    "Figi",
    "Finlandia",
    "Francia",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germania",
    "Ghana",
    "Grecia",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Ungheria",
    "Islanda",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Irlanda",
    "Israele",
    "Giamaica",
    "Giappone",
    "Giordania",
    "Kazakistan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kirghizistan",
    "Laos",
    "Lettonia",
    "Libano",
    "Lesotho",
    "Liberia",
    "Libia",
    "Liechtenstein",
    "Lituania",
    "Lussemburgo",
    "Macedonia del Nord",
    "Madagascar",
    "Malawi",
    "Malesia",
    "Maldive",
    "Mali",
    "Malta",
    "Isole Marshall",
    "Mauritania",
    "Mauritius",
    "Messico",
    "Micronesia",
    "Moldavia",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Marocco",
    "Mozambico",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Paesi Bassi",
    "Nuova Zelanda",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Corea del Nord",
    "Macedonia del Nord",
    "Norvegia",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestina",
    "Panama",
    "Papua Nuova Guinea",
    "Paraguay",
    "Perù",
    "Filippine",
    "Polonia",
    "Portogallo",
    "Qatar",
    "Romania",
    "Russia",
    "Ruanda",
    "Saint Kitts e Nevis",
    "Santa Lucia",
    "Saint Vincent e Grenadine",
    "Samoa",
    "San Marino",
    "São Tomé e Príncipe",
    "Arabia Saudita",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovacchia",
    "Slovenia",
    "Isole Salomone",
    "Somalia",
    "Sudafrica",
    "Corea del Sud",
    "Sudan del Sud",
    "Spagna",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Svezia",
    "Svizzera",
    "Siria",
    "Taiwan",
    "Tagikistan",
    "Tanzania",
    "Thailandia",
    "Timor Est",
    "Togo",
    "Tonga",
    "Trinidad e Tobago",
    "Tunisia",
    "Turchia",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ucraina",
    "Emirati Arabi Uniti",
    "Regno Unito",
    "Stati Uniti d'America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Città del Vaticano",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];

export default nazioniConBandiere;